### get user info
GET {{host-url}}
Cache-Control: no-cache
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}


### get user
GET {{host-url}}/user/test
Cache-Control: no-cache
Content-Type: application/json
Accept: application/json


### Signup new user
POST {{host-url}}/user/signup
Cache-Control: no-cache
Content-Type: application/json
Accept: application/json

{
  "email": "111222asdsa@dfsf.ru",
  "name": "asdasd",
  "password": "qwerty12345"
}


### get user info
POST {{auth-url}}/oauth/token
Content-Type: application/json
Accept: application/json

{
  "client_id": "vuejs",
  "client_secret": "vuejssecret",
  "grant_type": "password",
  "username": "admin@test1.ru",
  "password": "qwerty"
}

> {%
client.global.set('token', response.body.access_token);
client.global.set('refresh_token', response.body.refresh_token);
%}


###

